# Generated by Django 4.2.1 on 2024-08-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_user_avatar_remove_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
