# Generated by Django 4.2.1 on 2024-08-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_remove_user_avatar_remove_user_bio_remove_user_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
