# Generated by Django 4.2.1 on 2024-08-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_userprofile_name_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
