# Generated by Django 4.2.1 on 2024-08-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_category_category_name_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(
                default="post-2.jpg", null=True, upload_to="postImage"
            ),
        ),
    ]
