# Generated by Django 4.2.1 on 2024-08-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_post_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
